### ISSUE TITLE
[Bug]: atlassian-python-api 5.0.3 still incompatible — page lookup by title fails silently, emoji/width lost

### ISSUE THREAD

**Issue by joschneid** [sooperset/mcp-atlassian#1601]
### Prerequisites

- [x] I have searched the [existing issues](https://github.com/sooperset/mcp-atlassian/issues) to make sure this bug has not already been reported.
- [x] I have checked the [README](https://github.com/sooperset/mcp-atlassian/blob/main/README.md) for relevant information.

### Bug Description

`atlassian-python-api` 5.0.3 fixes the `/rest/api/1.0/...` path bug that #1589
pinned against, so it looks like a candidate for lifting the `<5.0.0` ceiling.
It isn't. On Confluence Data Center three v5 differences still break the current
code, and two of them are silent — the user gets a plausible but wrong answer
rather than an error:

1. **`confluence_get_page` by title + space reports the page as non-existent.**
   `get_page_by_title` renamed its first parameter `space` → `space_key`, so the
   call at `pages.py:570` (0.23.1: 544) raises `TypeError`. That is caught by
   `except (ValueError, TypeError)` at `pages.py:621` (0.23.1: 595), which
   returns `None`, and the server turns `None` into
   `"Page with title '…' not found in space '…'."`
   (`servers/confluence.py:384`). The page exists. Lookup by `page_id` is
   unaffected and works fine.

2. **`get_all_pages_from_space`** has the same rename, called at `pages.py:651`
   (0.23.1: 625). It sits in `get_space_pages()`, which has **no callers** in the
   package, so no tool reaches it today. Listed for completeness.

3. **Page emoji and page width are written but no longer read back.**
   `get_page_properties` returns a `list` on 5.0.3 and a `dict` on 4.0.7, while
   both consumers assume the dict shape — `pages.py:329` in `_get_page_emoji()`
   and `pages.py:487` in `_get_page_width()` (0.23.1: 328 / 461). The resulting
   `AttributeError` is swallowed by the broad `except Exception` in each
   function, so the field simply disappears from the response.

Filing this so the remaining blockers for a future v5 bump are documented. The
write path itself is not affected — see Actual Behavior.

### Steps to Reproduce

The pin prevents this in a normal install, so v5 has to be forced:

1. `pip install --no-deps "atlassian-python-api==5.0.3"` into the server's
   environment (`--no-deps` bypasses the `<5.0.0` constraint).
2. Restart the MCP server so the new library is loaded.
3. Call `confluence_get_page` with `title` + `space_key` and **no** `page_id`,
   using the title of a page that definitely exists.
4. Call `confluence_get_page` again for the same page, this time by `page_id`.
5. Create a page with an emoji and read it back:
   `confluence_create_page(space_key=…, title=…, content=…, emoji="🎯")`, then
   `confluence_get_page(page_id=<new id>)`.
6. For comparison, verify the property really was written, bypassing the
   library: `GET /rest/api/content/<page_id>/property`.
7. Downgrade to 4.0.7, restart, and repeat steps 3-5.

### Expected Behavior

Same results on 5.0.3 as on 4.0.7:

- Step 3 returns the page, identical to the `page_id` lookup in step 4.
- Step 5 returns the page including its `emoji` field.

### Actual Behavior

```shell
**Step 3 — page reported as missing (5.0.3):**


{"error": "Page with title '<title>' not found in space '<SPACE>'."}


The page exists. **Step 4** (same page by `page_id`) returns it completely on
5.0.3, which makes the failure look like a data problem rather than a library
incompatibility.

Underlying cause, with the signatures on 5.0.3 (`inspect.signature`, client
built with `cloud=False`):


get_page_by_title        -> ['space_key', 'title', 'kwargs']
get_all_pages_from_space -> ['space_key', 'kwargs']

TypeError: Server.get_page_by_title() missing 1 required positional
argument: 'space_key'


Renaming the keyword is **not** sufficient — with the new name the result is
missing both the id and the expanded body:


5.0.3, space_key=  ->  id=None,       body expanded=False
4.0.7, space=      ->  id=<page_id>,  body expanded=True


4.0.7 in turn rejects `space_key=` with `unexpected keyword argument`, so the two
versions have no common call form.

**Step 5 — emoji silently missing (5.0.3):** neither the `create_page` response
nor the subsequent `get_page` contains an `emoji` field. On 4.0.7 both return
`"emoji": "1f3af"`.

**Step 6 — the property was written correctly:**


GET /rest/api/content/<page_id>/property
  size: 2
  emoji-title-draft      = 1f3af
  emoji-title-published  = 1f3af


So the write path works and only the read-back is broken. Measured shapes:


4.0.7: dict with keys ['_links', 'limit', 'results', 'size', 'start']
5.0.3: list


Running the consumer snippet verbatim on a page that has properties:


properties = self.confluence.get_page_properties(page_id)
if not properties:
    return None
results = properties.get("results", [])



5.0.3:  list, length 2, truthy  ->  AttributeError:
                                    'list' object has no attribute 'get'
4.0.7:  dict, length 5          ->  ok, 2 results


On a page without properties the empty list is falsy and the code
short-circuits to `None` instead, so nothing is logged at all.

**What else I checked**

I bound the arguments of every `self.confluence.<method>(...)` call in
`mcp_atlassian/confluence/` against both versions' signatures — 45 calls, 4.0.7
clean, 5.0.3 two failures (findings 1 and 2). Three calls pass `**kwargs` and
can't be checked that way, so I exercised the whole write path against a live DC
instance: `create_page`, `update_page`, `set_page_label`, `add_comment`,
`remove_page` and `move_page` all work on 5.0.3. Note `create_page` still takes
`space=` — the rename hit only the two methods above.

**Not verified:** return shapes of the remaining read methods (I measured
`get_page_properties` and `get_page_by_title` explicitly), and
`get_all_pages_from_space` beyond its signature, since its only caller is never
called.

**Suggestion:** keep the `>=4.0.0,<5.0.0` ceiling. For a future v5 bump the known
work is the rename plus return shape of `get_page_by_title`, the rename in
`get_all_pages_from_space`, and list-vs-dict handling for `get_page_properties`
at both call sites. Independently of v5, the `except (ValueError, TypeError)` at
`pages.py:621` turning a library-level `TypeError` into "page not found" is worth
a look — it makes any future signature drift hard to diagnose. See also #1585
(Cloud class missing methods).
```

### mcp-atlassian Version

0.23.1 (findings also verified against main)

### Installation Method

From PyPI (pip install mcp-atlassian / uv add mcp-atlassian)

### Operating System

Linux (Specify distribution below if relevant)

### Python Version

3.14.6

### Atlassian Instance Type

Confluence Server / Data Center

### Client Application

Claude Code (MCP over stdio)
